export const availableCollections = [
    "CLASSIC KEBAB",
    "CLASSIC KEBAB MENU",
    "CHICKEN KEBAB",
    "CHICKEN KEBAB MENU",
    "STEAK KEBAB",
    "STEAK KEBAB MENU",
    "MIX KEBAB",
    "MIX KEBAB MENU",
    "NUGGETS",
    "NUGGETS MENU",
    "FALAFEL",
    "FALAFEL MENU",
    "MOZZARELLA",
    "MOZZARELLA MENU",
    "PRILOZI",
    "NAPITCI",
    "DESERT",
] as const;
